### ISSUE TITLE
aarch64 wheels support

### ISSUE THREAD

**Issue by junli-ccu** [urschrei/pypolyline#6]
We are using pypolyline in our python projects. Recently we need to migrate them to arm64 servers. Is it possible for you to provide aarch64 wheels?
If not, can you provide source code on pypi.org for us to build wheels?
If not, then I think the only option for us is to pre-build the wheels. I have been reading the [build_wheel.sh](https://github.com/urschrei/pypolyline/blob/master/ci/build_wheel.sh). It looks like it also depends on [polyline-ffi](https://github.com/urschrei/polyline-ffi). And there is not aarch binary for it. Do we also need to build it ourselves? Is this the right way to go?

Any information is appreciated.

**Comment by urschrei** [comment]
You'll have to be patient – I'm trying to get manylinux2014 aarch64 builds of libpolyline working, which should make building the wheels relatively straightforward – but it's taking a while and I don't have much spare time at the moment.

**Comment by junli-ccu** [comment]
Thanks for your response. Is there any way that I can help you with? Although I actually don't know too much about libpolyline, I do have access to arm64 machines to verify any script for you.
Or if you can give me some directions, I can try to come up with the script.

**Comment by urschrei** [comment]
libpolyline (in the polyline-ffi repo) is built using a tool called cross which executes Rust builds in a Docker container, which is required for manylinux compat. At the moment, the linker step is failing, but I don't know why – probably because the linker or target is specified incorrectly. By all means have a look! https://github.com/urschrei/polyline-ffi/commit/7d407c9ceb51ed0239e774cf1ce0be39459c1471

**Comment by urschrei** [comment]
aarch64 wheels now available on PyPI
